# Generated by Django 6.0.2 on 2026-04-15 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_user_unique_username_per_company_and_more'),
        ('contacts', '0003_alter_contact_unique_together_contact_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='accounts.company'),
        ),
        migrations.AlterField(
            model_name='contactgroup',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_groups', to='accounts.company'),
        ),
    ]
