# Generated by Django 6.0.2 on 2026-04-16 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_companytransaction_company'),
        ('contacts', '0004_alter_contact_company_alter_contactgroup_company'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='contact',
            name='unique_phone_per_company',
        ),
        migrations.AddField(
            model_name='contact',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['user'], name='contacts_co_user_id_a88208_idx'),
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.UniqueConstraint(fields=('user', 'phone'), name='unique_phone_per_user'),
        ),
    ]
