# Generated by Django 6.0.2 on 2026-04-15 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_user_unique_username_per_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companytransaction',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_transactions', to='accounts.company'),
        ),
    ]
