# Generated by Django 6.0.2 on 2026-08-31 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_companytransaction_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='companytransaction',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_company_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usercredittransaction',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_user_credit_transactions', to=settings.AUTH_USER_MODEL),
        ),
    ]
