# Generated by Django 6.0.2 on 2026-02-22 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], max_length=20),
        ),
    ]
