# Generated by Django 6.0.2 on 2026-02-22 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('messaging', '0003_campaign_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaign',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='campaign',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.company'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('scheduled', 'Programmée'), ('sent', 'Envoyée'), ('cancelled', 'Annulée')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='campaign',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='campaign',
            name='total_recipients',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contact',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.company'),
        ),
        migrations.AlterField(
            model_name='message',
            name='cost',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8),
        ),
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together={('company', 'phone')},
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['company', 'status'], name='messaging_c_company_8dbd22_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['company', 'phone'], name='messaging_c_company_13f73c_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['company', 'status'], name='messaging_m_company_838d3e_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sent_at'], name='messaging_m_sent_at_2aa227_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['scheduled_at'], name='messaging_m_schedul_9cca01_idx'),
        ),
    ]
