# Generated by Django 6.0.2 on 2026-03-15 21:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_companytransaction_options_and_more'),
        ('messaging', '0007_sender'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sender',
            name='user',
        ),
        migrations.AddField(
            model_name='sender',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sender',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_senders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sender',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.company'),
        ),
        migrations.AddField(
            model_name='sender',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_senders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sender',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('approved', 'ApprouvÃ©'), ('rejected', 'RefusÃ©')], default='pending', max_length=20),
        ),
    ]
