# Generated by Django 6.0.2 on 2026-03-15 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_companytransaction_options_and_more'),
        ('messaging', '0008_remove_sender_user_sender_approved_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sender',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company'),
        ),
        migrations.AlterField(
            model_name='sender',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Refusé')], default='pending', max_length=20),
        ),
    ]
