# Generated by Django 6.0.2 on 2026-03-24 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0009_alter_sender_company_alter_sender_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sender',
            name='name',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
