# Generated by Django 6.0.2 on 2026-04-15 14:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_companytransaction_company'),
        ('messaging', '0010_alter_sender_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='contact',
            name='messaging_c_company_13f73c_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='messaging_m_created_d51bc4_idx',
        ),
        migrations.AlterField(
            model_name='sender',
            name='name',
            field=models.CharField(max_length=15),
        ),
        migrations.AddConstraint(
            model_name='sender',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='unique_sender_per_company'),
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
