# Generated by Django 6.0.2 on 2026-07-30 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0013_alter_message_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sender_name',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
